import { StyleSheet } from 'react-native';

import { APP_THEME } from '@/constants/theme';
import { TEACHER_TITLE } from '@/components/teacher/teacher-tokens';

/** Light premium palette — монохром, акцент чёрным, без «синего пластика». */
export const DRILL = {
  canvas: APP_THEME.color.bg,
  card: APP_THEME.color.elevated,
  cardEdge: APP_THEME.color.borderStrong,
  well: APP_THEME.color.bg,
  wellEdge: APP_THEME.color.border,
  chip: APP_THEME.color.surfaceStrong,
  chipEdge: APP_THEME.color.border,
  chipActiveBg: APP_THEME.color.accentSoft,
  chipActiveEdge: APP_THEME.color.borderStrong,
  focusEdge: 'rgba(0, 0, 0, 0.28)',
  focusBg: 'rgba(0, 0, 0, 0.04)',
  successEdge: 'rgba(52, 199, 89, 0.38)',
  successBg: 'rgba(52, 199, 89, 0.09)',
  label: APP_THEME.color.mutedSoft,
  progress: APP_THEME.color.text,
  radiusCard: 32,
  radiusWell: 20,
  radiusControl: 16,
  radiusChip: 14,
} as const;

export const drillTaskStyles = StyleSheet.create({
  section: { gap: 12 },
  sectionLabel: {
    fontSize: 13,
    fontWeight: '500',
    letterSpacing: -0.06,
    color: DRILL.label,
    paddingHorizontal: 2,
  },
  promptSurface: {
    padding: 20,
    borderRadius: DRILL.radiusWell,
    backgroundColor: DRILL.well,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: DRILL.wellEdge,
  },
  promptPlain: {
    fontSize: 22,
    lineHeight: 30,
    fontWeight: '600',
    letterSpacing: -0.48,
    color: TEACHER_TITLE,
  },
  promptText: {
    fontSize: 22,
    lineHeight: 32,
    fontWeight: '600',
    letterSpacing: -0.4,
    color: TEACHER_TITLE,
  },
  inlineRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    rowGap: 10,
    columnGap: 4,
  },
  blankShell: {
    minWidth: 88,
    minHeight: 44,
    borderRadius: DRILL.radiusChip,
    backgroundColor: DRILL.chip,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: DRILL.chipEdge,
    paddingHorizontal: 12,
    justifyContent: 'center',
  },
  blankShellFocused: {
    borderColor: DRILL.focusEdge,
    backgroundColor: DRILL.focusBg,
  },
  blankShellFilled: {
    borderColor: APP_THEME.color.borderStrong,
    backgroundColor: APP_THEME.color.accentSoft,
  },
  blankInput: {
    minWidth: 60,
    fontSize: 18,
    fontWeight: '600',
    letterSpacing: -0.22,
    color: APP_THEME.color.text,
    textAlign: 'center',
    padding: 0,
  },
  blankFilledText: {
    fontSize: 18,
    fontWeight: '600',
    letterSpacing: -0.22,
    color: APP_THEME.color.text,
    textAlign: 'center',
  },
  blankPlaceholder: {
    color: APP_THEME.color.mutedSoft,
    fontWeight: '500',
  },
  bankRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  bankChip: {
    paddingHorizontal: 16,
    paddingVertical: 11,
    borderRadius: DRILL.radiusChip,
    backgroundColor: DRILL.chip,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: DRILL.chipEdge,
  },
  bankChipSelected: {
    borderColor: DRILL.chipActiveEdge,
    backgroundColor: DRILL.chipActiveBg,
  },
  bankChipUsed: { opacity: 0.32 },
  bankChipPressed: {
    backgroundColor: DRILL.chipActiveBg,
    borderColor: DRILL.chipActiveEdge,
  },
  bankChipText: {
    fontSize: 15,
    fontWeight: '500',
    letterSpacing: -0.12,
    color: APP_THEME.color.textSoft,
  },
  bankChipTextUsed: { color: APP_THEME.color.mutedFaint },
  numberedRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: DRILL.radiusControl,
    backgroundColor: DRILL.chip,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: DRILL.chipEdge,
  },
  numberedRowActive: {
    borderColor: DRILL.focusEdge,
    backgroundColor: DRILL.focusBg,
  },
  numberedRowFilled: {
    borderColor: DRILL.successEdge,
    backgroundColor: DRILL.successBg,
  },
  numberedLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: APP_THEME.color.mutedSoft,
    minWidth: 24,
    fontVariant: ['tabular-nums'],
  },
  numberedSentenceBody: {
    flex: 1,
  },
  numberedText: {
    flex: 1,
    fontSize: 17,
    lineHeight: 24,
    letterSpacing: -0.2,
    color: TEACHER_TITLE,
  },
  formBlock: { gap: 10 },
  formPrompt: {
    paddingVertical: 16,
    paddingHorizontal: 18,
    borderRadius: DRILL.radiusControl,
    backgroundColor: DRILL.chip,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: DRILL.chipEdge,
  },
  formPromptActive: {
    borderColor: DRILL.focusEdge,
    backgroundColor: DRILL.focusBg,
  },
  formPromptText: {
    fontSize: 18,
    lineHeight: 26,
    letterSpacing: -0.24,
    color: TEACHER_TITLE,
  },
  optionsCol: { gap: 10, paddingLeft: 4 },
  optionRow: {
    paddingVertical: 13,
    paddingHorizontal: 16,
    borderRadius: DRILL.radiusControl,
    backgroundColor: DRILL.well,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: DRILL.wellEdge,
  },
  optionRowSelected: {
    borderColor: DRILL.chipActiveEdge,
    backgroundColor: DRILL.chipActiveBg,
  },
  optionText: {
    fontSize: 16,
    lineHeight: 22,
    letterSpacing: -0.16,
    color: APP_THEME.color.textSoft,
  },
  optionTextSelected: {
    color: APP_THEME.color.text,
    fontWeight: '600',
  },
  readSelectCard: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 28,
    paddingHorizontal: 20,
    borderRadius: DRILL.radiusWell,
    backgroundColor: DRILL.well,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: DRILL.wellEdge,
  },
  readSelectWord: {
    fontSize: 28,
    fontWeight: '700',
    letterSpacing: -0.4,
    color: TEACHER_TITLE,
    textAlign: 'center',
  },
  readSelectRow: {
    flexDirection: 'row',
    gap: 10,
  },
  readSelectBtn: {
    flex: 1,
    minHeight: 50,
    borderRadius: DRILL.radiusControl,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: DRILL.chip,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: DRILL.chipEdge,
  },
  readSelectBtnActive: {
    borderColor: DRILL.focusEdge,
    backgroundColor: DRILL.focusBg,
  },
  readSelectBtnText: {
    fontSize: 15,
    fontWeight: '600',
    letterSpacing: -0.12,
    color: APP_THEME.color.textSoft,
  },
  readSelectBtnTextActive: {
    color: APP_THEME.color.text,
  },
  partialGapInput: {
    minWidth: 44,
    maxWidth: 88,
    minHeight: 36,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: DRILL.radiusChip,
    backgroundColor: DRILL.chip,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: DRILL.chipEdge,
    fontSize: 17,
    fontWeight: '600',
    letterSpacing: -0.2,
    color: APP_THEME.color.text,
    textAlign: 'center',
  },
  passageText: {
    fontSize: 16,
    lineHeight: 24,
    letterSpacing: -0.16,
    color: APP_THEME.color.textSoft,
  },
  imageGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    justifyContent: 'center',
  },
  imageCard: {
    width: '46%',
    borderRadius: DRILL.radiusWell,
    overflow: 'hidden',
    backgroundColor: DRILL.chip,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: DRILL.chipEdge,
  },
  imageCardActive: { borderColor: DRILL.focusEdge },
  imageCardFilled: { borderColor: DRILL.successEdge },
  imagePhoto: { width: '100%', height: 112 },
  imagePlaceholder: {
    height: 112,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: DRILL.well,
  },
  imageWord: {
    paddingVertical: 10,
    paddingHorizontal: 8,
    textAlign: 'center',
    fontSize: 14,
    fontWeight: '600',
    letterSpacing: -0.1,
    color: TEACHER_TITLE,
  },
  sentenceBuilt: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    paddingVertical: 16,
    paddingHorizontal: 18,
    borderRadius: DRILL.radiusControl,
    backgroundColor: DRILL.chip,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: DRILL.chipEdge,
    minHeight: 58,
  },
  sentenceBuiltText: {
    flex: 1,
    fontSize: 18,
    lineHeight: 26,
    letterSpacing: -0.22,
    color: TEACHER_TITLE,
  },
  sentenceReset: { padding: 4, marginTop: 2 },
  matchWrap: { flexDirection: 'row', gap: 12 },
  matchCol: { flex: 1, gap: 10 },
  matchItem: {
    paddingVertical: 14,
    paddingHorizontal: 14,
    borderRadius: DRILL.radiusControl,
    backgroundColor: DRILL.chip,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: DRILL.chipEdge,
    gap: 8,
  },
  matchItemRight: { backgroundColor: DRILL.well },
  matchItemActive: {
    borderColor: DRILL.focusEdge,
    backgroundColor: DRILL.focusBg,
  },
  matchItemMatched: {
    borderColor: DRILL.successEdge,
    backgroundColor: DRILL.successBg,
  },
  matchItemUsed: { opacity: 0.38 },
  matchText: {
    fontSize: 16,
    lineHeight: 22,
    letterSpacing: -0.14,
    color: TEACHER_TITLE,
  },
  matchLink: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  matchLinkText: {
    fontSize: 13,
    lineHeight: 18,
    color: APP_THEME.color.muted,
    flex: 1,
  },
  freeInput: {
    minHeight: 148,
    paddingVertical: 16,
    paddingHorizontal: 18,
    borderRadius: DRILL.radiusControl,
    backgroundColor: DRILL.chip,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: DRILL.chipEdge,
    fontSize: 17,
    lineHeight: 26,
    letterSpacing: -0.18,
    color: TEACHER_TITLE,
    textAlignVertical: 'top',
  },
});

export const drillShellStyles = StyleSheet.create({
  card: {
    borderRadius: DRILL.radiusCard,
    backgroundColor: DRILL.card,
    padding: 26,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: DRILL.cardEdge,
    gap: 22,
  },
  typeBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    paddingHorizontal: 11,
    paddingVertical: 6,
    borderRadius: APP_THEME.radius.pill,
    backgroundColor: APP_THEME.color.accentSoft,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: APP_THEME.color.border,
  },
  typeBadgeText: {
    fontSize: 11,
    fontWeight: '600',
    letterSpacing: 0.15,
    color: APP_THEME.color.textSoft,
  },
  cardStep: {
    fontSize: 12,
    color: APP_THEME.color.mutedSoft,
    fontVariant: ['tabular-nums'],
    fontWeight: '500',
  },
  instruction: {
    fontSize: 15,
    lineHeight: 21,
    letterSpacing: -0.14,
    color: APP_THEME.color.muted,
    marginTop: -8,
  },
  section: drillTaskStyles.section,
  sectionLabel: drillTaskStyles.sectionLabel,
  choicesCol: { gap: 12 },
  choiceRow: {
    minHeight: 58,
    borderRadius: DRILL.radiusControl,
    paddingHorizontal: 16,
    paddingVertical: 14,
    backgroundColor: DRILL.chip,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: DRILL.chipEdge,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  choiceRowSelected: {
    borderColor: DRILL.chipActiveEdge,
    backgroundColor: DRILL.chipActiveBg,
  },
  choiceRowDisabled: { opacity: 0.65 },
  choiceLetter: {
    width: 30,
    height: 30,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: APP_THEME.color.accentSoft,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: DRILL.chipEdge,
  },
  choiceLetterSelected: {
    backgroundColor: APP_THEME.color.text,
    borderColor: APP_THEME.color.text,
  },
  choiceLetterText: {
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 0.1,
    color: APP_THEME.color.mutedSoft,
  },
  choiceLetterTextSelected: { color: APP_THEME.color.bgSoft },
  choiceText: {
    flex: 1,
    fontSize: 17,
    lineHeight: 24,
    fontWeight: '400',
    letterSpacing: -0.2,
    color: APP_THEME.color.textSoft,
  },
  choiceTextSelected: {
    color: APP_THEME.color.text,
    fontWeight: '500',
  },
  progressTrack: {
    height: 2,
    borderRadius: 99,
    backgroundColor: APP_THEME.color.accentSoft,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    borderRadius: 99,
    backgroundColor: DRILL.progress,
  },
});
