import { Platform, StyleSheet } from 'react-native';

import { teacherMessageStyles } from '@/components/chat/chat-message-styles';
import { CHAT_MSG } from '@/constants/chat-message';
import { GAME_THEME } from '@/constants/game-theme';
import { APP_THEME } from '@/constants/theme';
import { TEACHER_MUTED, TEACHER_MUTED_SOFT, TEACHER_TITLE } from '@/components/teacher/teacher-tokens';

/** Subtle accent for teacher-specific positive feedback */
export const TEACHER_LESSON_ACCENT = GAME_THEME.color.ok;

export const teacherChatStyles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: GAME_THEME.color.cream,
  },
  content: {
    flex: 1,
  },
  lessonContext: {
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 4,
  },
  lessonBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 11,
    paddingVertical: 11,
    paddingHorizontal: 13,
    borderRadius: GAME_THEME.radius.panel,
    backgroundColor: GAME_THEME.color.cream,
    borderWidth: GAME_THEME.border.thin,
    borderColor: GAME_THEME.color.ink,
  },
  lessonBannerIcon: {
    width: 34,
    height: 34,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: GAME_THEME.color.sky,
    borderWidth: 2,
    borderColor: GAME_THEME.color.ink,
  },
  lessonBannerCol: {
    flex: 1,
    minWidth: 0,
  },
  lessonBannerEyebrow: {
    fontSize: GAME_THEME.type.micro,
    fontWeight: '800',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    color: 'rgba(26,26,26,0.45)',
    marginBottom: 2,
  },
  lessonContextIcon: {
    display: 'none',
  },
  lessonContextText: {
    fontSize: GAME_THEME.type.body,
    fontWeight: '700',
    lineHeight: 18,
    color: GAME_THEME.color.ink,
  },
  threadHost: {
    flex: 1,
    position: 'relative',
  },
  thread: {
    flex: 1,
  },
  threadContent: teacherMessageStyles.threadContent,
  dateWrap: {
    alignItems: 'center',
    marginVertical: 12,
  },
  dateChip: teacherMessageStyles.dateChip,
  dateChipText: teacherMessageStyles.dateChipText,
  teacherBlock: {
    alignSelf: 'stretch',
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    paddingRight: 6,
  },
  teacherRail: {
    display: 'none',
  },
  teacherAvatar: {
    width: 34,
    height: 34,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    marginTop: 2,
    backgroundColor: GAME_THEME.color.ink,
    borderWidth: 2,
    borderColor: GAME_THEME.color.sky,
  },
  teacherColumn: {
    flex: 1,
    minWidth: 0,
  },
  teacherCard: {
    alignSelf: 'stretch',
    paddingVertical: 14,
    paddingHorizontal: 15,
    borderRadius: GAME_THEME.radius.panel,
    backgroundColor: GAME_THEME.color.paper,
    borderWidth: 2,
    borderColor: GAME_THEME.color.ink,
    borderBottomWidth: 4,
    borderBottomColor: GAME_THEME.color.ink,
  },
  teacherCardTopEdge: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 3,
    borderTopLeftRadius: GAME_THEME.radius.panel,
    borderTopRightRadius: GAME_THEME.radius.panel,
    backgroundColor: GAME_THEME.color.sky,
  },
  teacherLabel: teacherMessageStyles.teacherLabel,
  teacherText: {
    ...CHAT_MSG.body,
    color: CHAT_MSG.incomingColor,
  },
  teacherTime: {
    ...CHAT_MSG.meta,
    marginTop: 9,
    marginLeft: 4,
  },
  teacherActionsGap: {
    height: 12,
  },
  teacherActions: {
    minHeight: 36,
  },
  studentWrap: teacherMessageStyles.studentWrap,
  studentCard: teacherMessageStyles.studentCard,
  studentText: teacherMessageStyles.studentText,
  studentTime: teacherMessageStyles.studentTime,
  typingCaption: teacherMessageStyles.typingCaption,
  typingDot: teacherMessageStyles.typingDot,
  imageMsgBody: teacherMessageStyles.imageMsgBody,
  imageCaptionIn: teacherMessageStyles.imageCaptionIn,
  imageCaptionOut: teacherMessageStyles.imageCaptionOut,
  exerciseModalBackdrop: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 18,
    backgroundColor: 'rgba(0, 0, 0, 0.65)',
  },
  exerciseModalScrim: {
    ...StyleSheet.absoluteFillObject,
  },
  exerciseModalCard: {
    width: '100%',
    maxWidth: 430,
    maxHeight: '88%',
    overflow: 'hidden',
    paddingTop: 16,
    paddingHorizontal: 16,
    paddingBottom: 16,
    borderRadius: APP_THEME.radius.sheet,
    backgroundColor: APP_THEME.color.elevated,
  },
  exerciseModalCardKeyboard: {
    position: 'absolute',
    left: 18,
    right: 18,
    width: undefined,
    maxWidth: undefined,
    maxHeight: undefined,
    paddingTop: 10,
    paddingBottom: 10,
  },
  exerciseBlobOne: {
    display: 'none',
  },
  exerciseBlobTwo: {
    display: 'none',
  },
  exerciseModalHandle: {
    alignSelf: 'center',
    width: 36,
    height: 4,
    borderRadius: 2,
    backgroundColor: APP_THEME.color.borderStrong,
    marginBottom: 14,
  },
  exerciseModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 14,
  },
  exerciseHero: {
    alignItems: 'center',
    paddingTop: 0,
    paddingBottom: 14,
    position: 'relative',
  },
  exerciseHeroKeyboard: {
    paddingBottom: 8,
  },
  exerciseMascot: {
    display: 'none',
  },
  exerciseMascotKeyboard: {
    display: 'none',
  },
  exerciseMascotEyeRow: {
    display: 'none',
  },
  exerciseMascotEye: {
    display: 'none',
  },
  exerciseMascotSmile: {
    display: 'none',
  },
  exerciseMascotIcon: {
    display: 'none',
  },
  exerciseModalIcon: {
    width: 38,
    height: 38,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: APP_THEME.color.elevatedSoft,
  },
  exerciseModalTitleCol: {
    flex: 1,
    minWidth: 0,
  },
  exerciseModalEyebrow: {
    ...APP_THEME.type.micro,
    color: APP_THEME.color.mutedSoft,
  },
  exerciseModalTitle: {
    marginTop: 4,
    fontSize: 24,
    fontWeight: '700',
    letterSpacing: -0.55,
    color: TEACHER_TITLE,
    textAlign: 'center',
  },
  exerciseModalTitleKeyboard: {
    marginTop: 0,
    fontSize: 20,
    letterSpacing: -0.4,
  },
  exerciseModalSubtitle: {
    maxWidth: 310,
    marginTop: 8,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '400',
    letterSpacing: -0.12,
    color: TEACHER_MUTED,
    textAlign: 'center',
  },
  exerciseProgressRow: {
    flexDirection: 'row',
    gap: 6,
    marginTop: 14,
  },
  exerciseProgressDot: {
    width: 28,
    height: 4,
    borderRadius: 99,
    backgroundColor: APP_THEME.color.accentSoft,
  },
  exerciseProgressDotActive: {
    width: 28,
    height: 4,
    borderRadius: 99,
    backgroundColor: APP_THEME.color.text,
  },
  exerciseCloseBtn: {
    position: 'absolute',
    top: 0,
    right: 0,
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: APP_THEME.color.elevatedSoft,
  },
  exerciseCloseBtnPressed: {
    opacity: 0.78,
  },
  exerciseModalScroll: {
    maxHeight: 430,
    flexShrink: 1,
  },
  exerciseModalScrollContent: {
    paddingBottom: 16,
    gap: 12,
  },
  exerciseTaskCard: {
    padding: 14,
    borderRadius: APP_THEME.radius.lg,
    backgroundColor: APP_THEME.color.elevatedSoft,
  },
  exerciseTaskLabel: {
    marginBottom: 6,
    ...APP_THEME.type.micro,
    color: APP_THEME.color.mutedSoft,
  },
  exerciseTaskText: {
    fontSize: 16,
    lineHeight: 23,
    fontWeight: '500',
    letterSpacing: -0.14,
    color: APP_THEME.color.textSoft,
  },
  exerciseAnswerBlock: {
    gap: 8,
  },
  exerciseAnswerLabel: {
    paddingHorizontal: 2,
    fontSize: 12,
    fontWeight: '600',
    letterSpacing: -0.06,
    color: TEACHER_MUTED,
  },
  exerciseAnswerInput: {
    minHeight: 118,
    maxHeight: 190,
    paddingVertical: 12,
    paddingHorizontal: 13,
    borderRadius: APP_THEME.radius.lg,
    backgroundColor: APP_THEME.color.bg,
    fontSize: 16,
    lineHeight: 22,
    letterSpacing: -0.2,
    color: TEACHER_TITLE,
  },
  exerciseResultCard: {
    padding: 14,
    borderRadius: APP_THEME.radius.lg,
  },
  exerciseResultGood: {
    backgroundColor: APP_THEME.color.successSoft,
  },
  exerciseResultNeedsWork: {
    backgroundColor: 'rgba(255, 159, 10, 0.12)',
  },
  exerciseResultHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 7,
  },
  exerciseResultTitle: {
    flex: 1,
    fontSize: 17,
    fontWeight: '600',
    letterSpacing: -0.34,
    color: TEACHER_TITLE,
  },
  exerciseResultText: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '400',
    letterSpacing: -0.12,
    color: TEACHER_MUTED,
  },
  exerciseIdealAnswer: {
    marginTop: 9,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '500',
    letterSpacing: -0.12,
    color: APP_THEME.color.textSoft,
  },
  exerciseNextBtn: {
    minHeight: 44,
    marginTop: 12,
    paddingHorizontal: 15,
    borderRadius: APP_THEME.radius.pill,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: APP_THEME.color.accent,
  },
  exerciseNextBtnPressed: {
    opacity: 0.88,
  },
  exerciseNextBtnDisabled: {
    opacity: 0.5,
  },
  exerciseNextText: {
    fontSize: 14,
    fontWeight: '600',
    letterSpacing: -0.14,
    color: APP_THEME.color.bg,
  },
  exerciseSubmitBtn: {
    minHeight: 50,
    marginTop: 10,
    borderRadius: APP_THEME.radius.pill,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: APP_THEME.color.accent,
  },
  exerciseSubmitBtnPressed: {
    opacity: 0.88,
  },
  exerciseSubmitBtnDisabled: {
    opacity: 0.4,
  },
  exerciseSubmitText: {
    fontSize: 15,
    fontWeight: '600',
    letterSpacing: -0.18,
    color: APP_THEME.color.bg,
  },
  xpRewardOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 30,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 28,
    backgroundColor: 'rgba(0, 0, 0, 0.45)',
  },
  xpRewardCard: {
    width: '100%',
    maxWidth: 320,
    overflow: 'hidden',
    alignItems: 'center',
    paddingTop: 24,
    paddingBottom: 22,
    paddingHorizontal: 24,
    borderRadius: APP_THEME.radius.sheet,
    backgroundColor: APP_THEME.color.elevated,
  },
  xpRewardGlowTop: {
    display: 'none',
  },
  xpRewardGlowBottom: {
    display: 'none',
  },
  xpRewardParticleOne: {
    display: 'none',
  },
  xpRewardParticleTwo: {
    display: 'none',
  },
  xpRewardParticleThree: {
    display: 'none',
  },
  xpRewardMedalOuter: {
    width: 72,
    height: 72,
    borderRadius: 36,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 14,
    backgroundColor: APP_THEME.color.elevatedSoft,
  },
  xpRewardMedal: {
    width: 56,
    height: 56,
    borderRadius: 28,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: APP_THEME.color.accent,
  },
  xpRewardCoinText: {
    fontSize: 16,
    fontWeight: '800',
    letterSpacing: -0.4,
    color: APP_THEME.color.bg,
  },
  xpRewardEyebrow: {
    ...APP_THEME.type.micro,
    color: APP_THEME.color.mutedSoft,
  },
  xpRewardValue: {
    marginTop: 4,
    fontSize: 36,
    fontWeight: '700',
    letterSpacing: -1,
    color: TEACHER_TITLE,
  },
  xpRewardText: {
    marginTop: 2,
    fontSize: 14,
    fontWeight: '400',
    letterSpacing: -0.12,
    color: TEACHER_MUTED,
  },
  xpRewardProgressTrack: {
    width: '100%',
    height: 4,
    marginTop: 16,
    borderRadius: 99,
    overflow: 'hidden',
    backgroundColor: APP_THEME.color.accentSoft,
  },
  xpRewardProgressFill: {
    width: '72%',
    height: '100%',
    borderRadius: 99,
    backgroundColor: APP_THEME.color.text,
  },
});
