import { StyleSheet } from 'react-native';

import { GAME_THEME } from '@/constants/game-theme';

/** Game-world drill palette — ink outlines, paper surfaces, SNES bevel. */
export const DRILL = {
  canvas: GAME_THEME.color.sky,
  card: GAME_THEME.color.cream,
  cardEdge: GAME_THEME.color.ink,
  well: GAME_THEME.color.paper,
  wellEdge: GAME_THEME.color.ink,
  chip: GAME_THEME.color.paper,
  chipEdge: GAME_THEME.color.ink,
  chipActiveBg: GAME_THEME.color.paperWarm,
  chipActiveEdge: GAME_THEME.color.ink,
  focusEdge: GAME_THEME.color.ink,
  focusBg: GAME_THEME.color.paperWarm,
  successEdge: GAME_THEME.color.ink,
  successBg: 'rgba(138,255,168,0.28)',
  label: 'rgba(26,26,26,0.5)',
  progress: GAME_THEME.color.phosphor,
  radiusCard: 0,
  radiusWell: 6,
  radiusControl: 6,
  radiusChip: 6,
} as const;

export const drillTaskStyles = StyleSheet.create({
  section: { gap: 12 },
  sectionLabel: {
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
    color: DRILL.label,
    paddingHorizontal: 2,
  },
  promptSurface: {
    padding: 18,
    borderRadius: DRILL.radiusWell,
    backgroundColor: DRILL.well,
    borderWidth: GAME_THEME.border.thick,
    borderColor: DRILL.wellEdge,
  },
  promptPlain: {
    fontSize: 22,
    lineHeight: 30,
    fontWeight: '800',
    letterSpacing: -0.4,
    color: GAME_THEME.color.ink,
  },
  promptText: {
    fontSize: 22,
    lineHeight: 32,
    fontWeight: '800',
    letterSpacing: -0.35,
    color: GAME_THEME.color.ink,
  },
  inlineRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    rowGap: 10,
    columnGap: 4,
  },
  blankShell: {
    minWidth: 88,
    minHeight: 44,
    borderRadius: DRILL.radiusChip,
    backgroundColor: GAME_THEME.color.cream,
    borderWidth: GAME_THEME.border.thin,
    borderColor: DRILL.chipEdge,
    borderBottomWidth: 3,
    borderBottomColor: GAME_THEME.color.goldLip,
    paddingHorizontal: 12,
    justifyContent: 'center',
  },
  blankShellFocused: {
    borderColor: DRILL.focusEdge,
    backgroundColor: DRILL.focusBg,
  },
  blankShellFilled: {
    borderColor: DRILL.chipActiveEdge,
    backgroundColor: DRILL.chipActiveBg,
  },
  blankInput: {
    minWidth: 60,
    fontSize: 18,
    fontWeight: '800',
    letterSpacing: -0.22,
    color: GAME_THEME.color.ink,
    textAlign: 'center',
    padding: 0,
  },
  blankFilledText: {
    fontSize: 18,
    fontWeight: '800',
    letterSpacing: -0.22,
    color: GAME_THEME.color.ink,
    textAlign: 'center',
  },
  blankPlaceholder: {
    color: 'rgba(26,26,26,0.35)',
    fontWeight: '600',
  },
  bankRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  bankChip: {
    paddingHorizontal: 14,
    paddingVertical: 11,
    borderRadius: DRILL.radiusChip,
    backgroundColor: GAME_THEME.color.cream,
    borderWidth: GAME_THEME.border.thin,
    borderColor: DRILL.chipEdge,
    borderBottomWidth: 3,
    borderBottomColor: GAME_THEME.color.goldLip,
  },
  bankChipSelected: {
    borderColor: DRILL.chipActiveEdge,
    backgroundColor: DRILL.chipActiveBg,
  },
  bankChipUsed: { opacity: 0.32 },
  bankChipPressed: {
    backgroundColor: DRILL.chipActiveBg,
    borderColor: DRILL.chipActiveEdge,
    transform: [{ translateY: 1 }],
  },
  bankChipText: {
    fontSize: 15,
    fontWeight: '800',
    letterSpacing: -0.1,
    color: GAME_THEME.color.ink,
  },
  bankChipTextUsed: { color: 'rgba(26,26,26,0.35)' },
  numberedRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    paddingVertical: 14,
    paddingHorizontal: 14,
    borderRadius: DRILL.radiusControl,
    backgroundColor: DRILL.chip,
    borderWidth: GAME_THEME.border.thin,
    borderColor: DRILL.chipEdge,
  },
  numberedRowActive: {
    borderColor: DRILL.focusEdge,
    backgroundColor: DRILL.focusBg,
  },
  numberedRowFilled: {
    borderColor: DRILL.successEdge,
    backgroundColor: DRILL.successBg,
  },
  numberedLabel: {
    fontSize: 14,
    fontWeight: '900',
    color: 'rgba(26,26,26,0.45)',
    minWidth: 24,
    fontVariant: ['tabular-nums'],
  },
  numberedSentenceBody: {
    flex: 1,
  },
  numberedText: {
    flex: 1,
    fontSize: 17,
    lineHeight: 24,
    letterSpacing: -0.2,
    fontWeight: '600',
    color: GAME_THEME.color.ink,
  },
  formBlock: { gap: 10 },
  formPrompt: {
    paddingVertical: 16,
    paddingHorizontal: 16,
    borderRadius: DRILL.radiusControl,
    backgroundColor: DRILL.chip,
    borderWidth: GAME_THEME.border.thin,
    borderColor: DRILL.chipEdge,
  },
  formPromptActive: {
    borderColor: DRILL.focusEdge,
    backgroundColor: DRILL.focusBg,
  },
  formPromptText: {
    fontSize: 18,
    lineHeight: 26,
    letterSpacing: -0.24,
    fontWeight: '700',
    color: GAME_THEME.color.ink,
  },
  optionsCol: { gap: 10, paddingLeft: 0 },
  optionRow: {
    paddingVertical: 13,
    paddingHorizontal: 14,
    borderRadius: DRILL.radiusControl,
    backgroundColor: GAME_THEME.color.cream,
    borderWidth: GAME_THEME.border.thin,
    borderColor: DRILL.wellEdge,
    borderBottomWidth: 3,
    borderBottomColor: GAME_THEME.color.goldLip,
  },
  optionRowSelected: {
    borderColor: DRILL.chipActiveEdge,
    backgroundColor: DRILL.chipActiveBg,
  },
  optionText: {
    fontSize: 16,
    lineHeight: 22,
    letterSpacing: -0.16,
    fontWeight: '700',
    color: GAME_THEME.color.ink,
  },
  optionTextSelected: {
    color: GAME_THEME.color.ink,
    fontWeight: '900',
  },
  readSelectCard: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 28,
    paddingHorizontal: 20,
    borderRadius: DRILL.radiusWell,
    backgroundColor: DRILL.well,
    borderWidth: GAME_THEME.border.thick,
    borderColor: DRILL.wellEdge,
  },
  readSelectWord: {
    fontSize: 28,
    fontWeight: '900',
    letterSpacing: -0.4,
    color: GAME_THEME.color.ink,
    textAlign: 'center',
  },
  readSelectRow: {
    flexDirection: 'row',
    gap: 10,
  },
  readSelectBtn: {
    flex: 1,
    minHeight: 50,
    borderRadius: DRILL.radiusControl,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: GAME_THEME.color.cream,
    borderWidth: GAME_THEME.border.thin,
    borderColor: DRILL.chipEdge,
    borderBottomWidth: 3,
    borderBottomColor: GAME_THEME.color.goldLip,
  },
  readSelectBtnActive: {
    borderColor: DRILL.focusEdge,
    backgroundColor: DRILL.focusBg,
  },
  readSelectBtnText: {
    fontSize: 15,
    fontWeight: '800',
    letterSpacing: -0.12,
    color: GAME_THEME.color.ink,
  },
  readSelectBtnTextActive: {
    color: GAME_THEME.color.ink,
  },
  partialGapInput: {
    minWidth: 44,
    maxWidth: 88,
    minHeight: 36,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: DRILL.radiusChip,
    backgroundColor: GAME_THEME.color.cream,
    borderWidth: GAME_THEME.border.thin,
    borderColor: DRILL.chipEdge,
    fontSize: 17,
    fontWeight: '800',
    letterSpacing: -0.2,
    color: GAME_THEME.color.ink,
    textAlign: 'center',
  },
  passageText: {
    fontSize: 16,
    lineHeight: 24,
    letterSpacing: -0.16,
    fontWeight: '600',
    color: GAME_THEME.color.ink,
  },
  imageGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    justifyContent: 'center',
  },
  imageCard: {
    width: '46%',
    borderRadius: DRILL.radiusWell,
    overflow: 'hidden',
    backgroundColor: DRILL.chip,
    borderWidth: GAME_THEME.border.thin,
    borderColor: DRILL.chipEdge,
  },
  imageCardActive: { borderColor: DRILL.focusEdge },
  imageCardFilled: { borderColor: DRILL.successEdge, backgroundColor: DRILL.successBg },
  imagePhoto: { width: '100%', height: 112 },
  imagePlaceholder: {
    height: 112,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: DRILL.well,
  },
  imageWord: {
    paddingVertical: 10,
    paddingHorizontal: 8,
    textAlign: 'center',
    fontSize: 14,
    fontWeight: '800',
    letterSpacing: -0.1,
    color: GAME_THEME.color.ink,
  },
  sentenceBuilt: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    paddingVertical: 16,
    paddingHorizontal: 16,
    borderRadius: DRILL.radiusControl,
    backgroundColor: DRILL.chip,
    borderWidth: GAME_THEME.border.thin,
    borderColor: DRILL.chipEdge,
    minHeight: 58,
  },
  sentenceBuiltText: {
    flex: 1,
    fontSize: 18,
    lineHeight: 26,
    letterSpacing: -0.22,
    fontWeight: '700',
    color: GAME_THEME.color.ink,
  },
  sentenceReset: { padding: 4, marginTop: 2 },
  matchWrap: { flexDirection: 'row', gap: 12 },
  matchCol: { flex: 1, gap: 10 },
  matchItem: {
    paddingVertical: 14,
    paddingHorizontal: 12,
    borderRadius: DRILL.radiusControl,
    backgroundColor: GAME_THEME.color.cream,
    borderWidth: GAME_THEME.border.thin,
    borderColor: DRILL.chipEdge,
    borderBottomWidth: 3,
    borderBottomColor: GAME_THEME.color.goldLip,
    gap: 8,
  },
  matchItemRight: { backgroundColor: DRILL.well },
  matchItemActive: {
    borderColor: DRILL.focusEdge,
    backgroundColor: DRILL.focusBg,
  },
  matchItemMatched: {
    borderColor: DRILL.successEdge,
    backgroundColor: DRILL.successBg,
  },
  matchItemUsed: { opacity: 0.38 },
  matchText: {
    fontSize: 16,
    lineHeight: 22,
    letterSpacing: -0.14,
    fontWeight: '700',
    color: GAME_THEME.color.ink,
  },
  matchLink: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  matchLinkText: {
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '600',
    color: 'rgba(26,26,26,0.5)',
    flex: 1,
  },
  freeInput: {
    minHeight: 120,
    paddingVertical: 14,
    paddingHorizontal: 14,
    borderRadius: DRILL.radiusControl,
    backgroundColor: DRILL.well,
    borderWidth: GAME_THEME.border.thin,
    borderColor: DRILL.wellEdge,
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '600',
    color: GAME_THEME.color.ink,
    textAlignVertical: 'top',
  },
});

export const drillShellStyles = StyleSheet.create({
  card: {
    borderRadius: 0,
    backgroundColor: 'transparent',
    padding: 0,
    borderWidth: 0,
    gap: 18,
    flex: 1,
  },
  typeBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 4,
    backgroundColor: GAME_THEME.color.sky,
    borderWidth: GAME_THEME.border.thin,
    borderColor: GAME_THEME.color.ink,
  },
  typeBadgeText: {
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
    color: GAME_THEME.color.cream,
  },
  cardStep: {
    fontSize: 12,
    color: 'rgba(26,26,26,0.45)',
    fontVariant: ['tabular-nums'],
    fontWeight: '800',
    letterSpacing: 0.3,
  },
  instruction: {
    fontSize: 15,
    lineHeight: 21,
    letterSpacing: -0.1,
    fontWeight: '700',
    color: 'rgba(26,26,26,0.55)',
  },
  section: drillTaskStyles.section,
  sectionLabel: drillTaskStyles.sectionLabel,
  choicesCol: { gap: 10 },
  choiceRow: {
    minHeight: 56,
    borderRadius: DRILL.radiusControl,
    paddingHorizontal: 14,
    paddingVertical: 12,
    backgroundColor: GAME_THEME.color.cream,
    borderWidth: GAME_THEME.border.thin,
    borderColor: DRILL.chipEdge,
    borderBottomWidth: 4,
    borderBottomColor: GAME_THEME.color.goldLip,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  choiceRowSelected: {
    borderColor: GAME_THEME.color.ink,
    backgroundColor: DRILL.chipActiveBg,
    borderBottomColor: GAME_THEME.color.ink,
  },
  choiceRowDisabled: { opacity: 0.65 },
  choiceLetter: {
    width: 28,
    height: 28,
    borderRadius: 4,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: GAME_THEME.color.paper,
    borderWidth: 2,
    borderColor: GAME_THEME.color.ink,
  },
  choiceLetterSelected: {
    backgroundColor: GAME_THEME.color.ink,
    borderColor: GAME_THEME.color.ink,
  },
  choiceLetterText: {
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 0.2,
    color: GAME_THEME.color.ink,
  },
  choiceLetterTextSelected: { color: GAME_THEME.color.cream },
  choiceText: {
    flex: 1,
    fontSize: 17,
    lineHeight: 24,
    fontWeight: '700',
    letterSpacing: -0.2,
    color: GAME_THEME.color.ink,
  },
  choiceTextSelected: {
    color: GAME_THEME.color.ink,
    fontWeight: '900',
  },
  progressTrack: {
    height: 8,
    backgroundColor: 'rgba(26,26,26,0.12)',
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    backgroundColor: DRILL.progress,
  },
});
