import type { CompanionChatApiLanguage } from '@/types/companion-chat-api';
import type { PlacementQuestionKind } from '@/types/placement-api';

export type LocalPlacementQuestion = {
  id: string;
  kind: PlacementQuestionKind;
  section: string;
  difficulty: number;
  instruction: string;
  prompt: string;
  choices: string[];
  correctChoice: string;
};

const english: LocalPlacementQuestion[] = [
  {
    id: 'en-1',
    kind: 'choose_translation',
    section: 'vocabulary',
    difficulty: 4,
    instruction: 'Choose the best translation.',
    prompt: 'hello',
    choices: ['привет', 'пока', 'спасибо', 'да'],
    correctChoice: 'привет',
  },
  {
    id: 'en-2',
    kind: 'select_missing_word',
    section: 'grammar',
    difficulty: 6,
    instruction: 'Pick the word that fits.',
    prompt: 'She ___ to work every day.',
    choices: ['go', 'goes', 'going', 'gone'],
    correctChoice: 'goes',
  },
  {
    id: 'en-3',
    kind: 'choose_translation',
    section: 'phrases',
    difficulty: 8,
    instruction: 'Choose the best translation.',
    prompt: 'Nice to meet you',
    choices: ['До свидания', 'Приятно познакомиться', 'Как дела?', 'Извините'],
    correctChoice: 'Приятно познакомиться',
  },
  {
    id: 'en-4',
    kind: 'multiple_choice',
    section: 'comprehension',
    difficulty: 10,
    instruction: 'What does the sentence mean?',
    prompt: 'I have been learning English for two years.',
    choices: [
      'I have been learning English for about two years.',
      'I have been learning English for about two months.',
      'I stopped learning English two years ago.',
      'I will start learning English in two years.',
    ],
    correctChoice: 'I have been learning English for about two years.',
  },
  {
    id: 'en-5',
    kind: 'select_missing_word',
    section: 'grammar',
    difficulty: 12,
    instruction: 'Pick the correct form.',
    prompt: 'If I ___ more time, I would travel more.',
    choices: ['have', 'had', 'will have', 'having'],
    correctChoice: 'had',
  },
  {
    id: 'en-6',
    kind: 'choose_translation',
    section: 'vocabulary',
    difficulty: 14,
    instruction: 'Choose the best translation.',
    prompt: 'reliable',
    choices: ['надёжный', 'быстрый', 'дорогой', 'громкий'],
    correctChoice: 'надёжный',
  },
  {
    id: 'en-7',
    kind: 'multiple_choice',
    section: 'comprehension',
    difficulty: 16,
    instruction: 'Choose the closest meaning.',
    prompt: 'She turned down the job offer.',
    choices: [
      'She rejected the offer.',
      'She accepted the offer.',
      'She postponed the offer.',
      'She reconsidered the offer.',
    ],
    correctChoice: 'She rejected the offer.',
  },
  {
    id: 'en-8',
    kind: 'select_missing_word',
    section: 'grammar',
    difficulty: 18,
    instruction: 'Pick the best option.',
    prompt: 'The report ___ by the team yesterday.',
    choices: ['was finished', 'finished', 'has finish', 'finishing'],
    correctChoice: 'was finished',
  },
  {
    id: 'en-9',
    kind: 'choose_translation',
    section: 'phrases',
    difficulty: 20,
    instruction: 'Choose the best translation.',
    prompt: 'It depends on the circumstances.',
    choices: ['Это зависит от обстоятельств.', 'Это всегда так.', 'Мне всё равно.', 'Я не уверен.'],
    correctChoice: 'Это зависит от обстоятельств.',
  },
  {
    id: 'en-10',
    kind: 'multiple_choice',
    section: 'comprehension',
    difficulty: 22,
    instruction: 'What is implied?',
    prompt: 'Had I known about the delay, I would have left earlier.',
    choices: [
      'I did not know about the delay and left too late.',
      'I knew about the delay but still left too late.',
      'I knew about the delay and left on time.',
      'I did not know about the delay but left on time.',
    ],
    correctChoice: 'I did not know about the delay and left too late.',
  },
  {
    id: 'en-11',
    kind: 'select_missing_word',
    section: 'grammar',
    difficulty: 24,
    instruction: 'Pick the most natural option.',
    prompt: 'Scarcely ___ the meeting begun when the fire alarm went off.',
    choices: ['had', 'has', 'was', 'did'],
    correctChoice: 'had',
  },
  {
    id: 'en-12',
    kind: 'choose_translation',
    section: 'vocabulary',
    difficulty: 15,
    instruction: 'Choose the best translation.',
    prompt: 'achievement',
    choices: ['достижение', 'ошибка', 'план', 'вопрос'],
    correctChoice: 'достижение',
  },
];

const french: LocalPlacementQuestion[] = [
  {
    id: 'fr-1',
    kind: 'choose_translation',
    section: 'vocabulary',
    difficulty: 4,
    instruction: 'Choose the best translation.',
    prompt: 'bonjour',
    choices: ['hello', 'goodbye', 'please', 'thanks'],
    correctChoice: 'hello',
  },
  {
    id: 'fr-2',
    kind: 'select_missing_word',
    section: 'grammar',
    difficulty: 7,
    instruction: 'Pick the word that fits.',
    prompt: 'Je ___ français.',
    choices: ['parle', 'parles', 'parlons', 'parlez'],
    correctChoice: 'parle',
  },
  {
    id: 'fr-3',
    kind: 'choose_translation',
    section: 'phrases',
    difficulty: 9,
    instruction: 'Choose the best translation.',
    prompt: 'Comment ça va ?',
    choices: ['How are you?', 'Where are you?', 'What time is it?', 'See you later!'],
    correctChoice: 'How are you?',
  },
  {
    id: 'fr-4',
    kind: 'multiple_choice',
    section: 'comprehension',
    difficulty: 11,
    instruction: 'What does it mean?',
    prompt: 'Il pleut depuis ce matin.',
    choices: [
      'It has been raining since this morning.',
      'It has been raining since yesterday evening.',
      'It stopped raining this morning.',
      'It started raining this morning.',
    ],
    correctChoice: 'It has been raining since this morning.',
  },
  {
    id: 'fr-5',
    kind: 'select_missing_word',
    section: 'grammar',
    difficulty: 13,
    instruction: 'Pick the correct form.',
    prompt: 'Hier, nous ___ au cinéma.',
    choices: ['sommes allés', 'allons', 'irons', 'allions'],
    correctChoice: 'sommes allés',
  },
  {
    id: 'fr-6',
    kind: 'choose_translation',
    section: 'vocabulary',
    difficulty: 15,
    instruction: 'Choose the best translation.',
    prompt: 'cependant',
    choices: ['however', 'because', 'always', 'never'],
    correctChoice: 'however',
  },
  {
    id: 'fr-7',
    kind: 'multiple_choice',
    section: 'comprehension',
    difficulty: 17,
    instruction: 'Choose the closest meaning.',
    prompt: 'Il s\'en est fallu de peu.',
    choices: ['It was a close call.', 'It was easy.', 'It failed completely.', 'It happened long ago.'],
    correctChoice: 'It was a close call.',
  },
  {
    id: 'fr-8',
    kind: 'select_missing_word',
    section: 'grammar',
    difficulty: 19,
    instruction: 'Pick the best option.',
    prompt: 'Si j\'avais su, je ___ plus tôt.',
    choices: ['serais parti', 'partirais', 'partais', 'suis parti'],
    correctChoice: 'serais parti',
  },
  {
    id: 'fr-9',
    kind: 'choose_translation',
    section: 'phrases',
    difficulty: 21,
    instruction: 'Choose the best translation.',
    prompt: 'Je n\'y suis pour rien.',
    choices: ['It\'s not my fault.', 'I am lost.', 'I agree completely.', 'I am ready.'],
    correctChoice: 'It\'s not my fault.',
  },
  {
    id: 'fr-10',
    kind: 'multiple_choice',
    section: 'comprehension',
    difficulty: 23,
    instruction: 'What is implied?',
    prompt: 'Bien qu\'il soit fatigué, il a terminé le projet.',
    choices: ['He finished despite being tired.', 'He stopped because he was tired.', 'He was not tired.', 'He did not finish.'],
    correctChoice: 'He finished despite being tired.',
  },
  {
    id: 'fr-11',
    kind: 'select_missing_word',
    section: 'grammar',
    difficulty: 24,
    instruction: 'Pick the most natural option.',
    prompt: 'C\'est le livre ___ je t\'ai parlé.',
    choices: ['dont', 'que', 'où', 'qui'],
    correctChoice: 'dont',
  },
  {
    id: 'fr-12',
    kind: 'choose_translation',
    section: 'vocabulary',
    difficulty: 10,
    instruction: 'Choose the best translation.',
    prompt: 'demain',
    choices: ['tomorrow', 'yesterday', 'today', 'never'],
    correctChoice: 'tomorrow',
  },
];

const german: LocalPlacementQuestion[] = [
  {
    id: 'de-1',
    kind: 'choose_translation',
    section: 'vocabulary',
    difficulty: 4,
    instruction: 'Choose the best translation.',
    prompt: 'Guten Tag',
    choices: ['Good day', 'Good night', 'Goodbye', 'Please'],
    correctChoice: 'Good day',
  },
  {
    id: 'de-2',
    kind: 'select_missing_word',
    section: 'grammar',
    difficulty: 7,
    instruction: 'Pick the word that fits.',
    prompt: 'Ich ___ aus Berlin.',
    choices: ['komme', 'kommt', 'kommen', 'kommst'],
    correctChoice: 'komme',
  },
  {
    id: 'de-3',
    kind: 'choose_translation',
    section: 'phrases',
    difficulty: 9,
    instruction: 'Choose the best translation.',
    prompt: 'Wie geht es dir?',
    choices: ['How are you?', 'Where do you live?', 'What is your name?', 'See you soon!'],
    correctChoice: 'How are you?',
  },
  {
    id: 'de-4',
    kind: 'multiple_choice',
    section: 'comprehension',
    difficulty: 12,
    instruction: 'What does it mean?',
    prompt: 'Ich habe gestern gearbeitet.',
    choices: ['I worked yesterday.', 'I work every day.', 'I will work tomorrow.', 'I am working now.'],
    correctChoice: 'I worked yesterday.',
  },
  {
    id: 'de-5',
    kind: 'select_missing_word',
    section: 'grammar',
    difficulty: 14,
    instruction: 'Pick the correct form.',
    prompt: 'Wenn ich Zeit ___, reise ich gern.',
    choices: ['hätte', 'habe', 'hatte', 'haben'],
    correctChoice: 'hätte',
  },
  {
    id: 'de-6',
    kind: 'choose_translation',
    section: 'vocabulary',
    difficulty: 16,
    instruction: 'Choose the best translation.',
    prompt: 'trotzdem',
    choices: ['nevertheless', 'because', 'before', 'under'],
    correctChoice: 'nevertheless',
  },
  {
    id: 'de-7',
    kind: 'multiple_choice',
    section: 'comprehension',
    difficulty: 18,
    instruction: 'Choose the closest meaning.',
    prompt: 'Er hat den Termin absagen müssen.',
    choices: ['He had to cancel the appointment.', 'He confirmed the appointment.', 'He forgot the time.', 'He arrived early.'],
    correctChoice: 'He had to cancel the appointment.',
  },
  {
    id: 'de-8',
    kind: 'select_missing_word',
    section: 'grammar',
    difficulty: 20,
    instruction: 'Pick the best option.',
    prompt: 'Das Buch, ___ ich gelesen habe, war spannend.',
    choices: ['das', 'der', 'die', 'den'],
    correctChoice: 'das',
  },
  {
    id: 'de-9',
    kind: 'choose_translation',
    section: 'phrases',
    difficulty: 22,
    instruction: 'Choose the best translation.',
    prompt: 'Das liegt auf der Hand.',
    choices: ['That\'s obvious.', 'That\'s impossible.', 'That\'s expensive.', 'That\'s far away.'],
    correctChoice: 'That\'s obvious.',
  },
  {
    id: 'de-10',
    kind: 'multiple_choice',
    section: 'comprehension',
    difficulty: 24,
    instruction: 'What is implied?',
    prompt: 'Hätte ich früher gewusst, wäre ich schon weg.',
    choices: ['I found out too late.', 'I knew from the start.', 'I am still here.', 'I never planned to leave.'],
    correctChoice: 'I found out too late.',
  },
  {
    id: 'de-11',
    kind: 'select_missing_word',
    section: 'grammar',
    difficulty: 11,
    instruction: 'Pick the correct article.',
    prompt: '___ Apfel ist rot.',
    choices: ['Der', 'Die', 'Das', 'Den'],
    correctChoice: 'Der',
  },
  {
    id: 'de-12',
    kind: 'choose_translation',
    section: 'vocabulary',
    difficulty: 8,
    instruction: 'Choose the best translation.',
    prompt: 'danke',
    choices: ['thanks', 'please', 'sorry', 'hello'],
    correctChoice: 'thanks',
  },
];

const chinese: LocalPlacementQuestion[] = [
  {
    id: 'zh-1',
    kind: 'choose_translation',
    section: 'vocabulary',
    difficulty: 4,
    instruction: 'Choose the best translation.',
    prompt: '你好 (nǐ hǎo)',
    choices: ['Hello', 'Goodbye', 'Thanks', 'Sorry'],
    correctChoice: 'Hello',
  },
  {
    id: 'zh-2',
    kind: 'select_missing_word',
    section: 'grammar',
    difficulty: 7,
    instruction: 'Pick the word that fits.',
    prompt: '我___学生。(wǒ ___ xuésheng)',
    choices: ['是 (shì)', '有 (yǒu)', '在 (zài)', '去 (qù)'],
    correctChoice: '是 (shì)',
  },
  {
    id: 'zh-3',
    kind: 'choose_translation',
    section: 'phrases',
    difficulty: 9,
    instruction: 'Choose the best translation.',
    prompt: '多少钱？(duōshao qián?)',
    choices: ['How much does it cost?', 'What time is it?', 'Where are you?', 'How old are you?'],
    correctChoice: 'How much does it cost?',
  },
  {
    id: 'zh-4',
    kind: 'multiple_choice',
    section: 'comprehension',
    difficulty: 11,
    instruction: 'What does it mean?',
    prompt: '我明天去北京。(wǒ míngtiān qù Běijīng)',
    choices: ['I will go to Beijing tomorrow.', 'I went to Beijing yesterday.', 'I live in Beijing.', 'I don\'t like Beijing.'],
    correctChoice: 'I will go to Beijing tomorrow.',
  },
  {
    id: 'zh-5',
    kind: 'select_missing_word',
    section: 'grammar',
    difficulty: 13,
    instruction: 'Pick the correct measure word.',
    prompt: '一___书 (yī ___ shū)',
    choices: ['本 (běn)', '个 (gè)', '张 (zhāng)', '条 (tiáo)'],
    correctChoice: '本 (běn)',
  },
  {
    id: 'zh-6',
    kind: 'choose_translation',
    section: 'vocabulary',
    difficulty: 15,
    instruction: 'Choose the best translation.',
    prompt: '虽然 (suīrán)',
    choices: ['although', 'because', 'but', 'if'],
    correctChoice: 'although',
  },
  {
    id: 'zh-7',
    kind: 'multiple_choice',
    section: 'comprehension',
    difficulty: 17,
    instruction: 'Choose the closest meaning.',
    prompt: '他还没来。(tā hái méi lái)',
    choices: ['He hasn\'t come yet.', 'He already left.', 'He is here now.', 'He will never come.'],
    correctChoice: 'He hasn\'t come yet.',
  },
  {
    id: 'zh-8',
    kind: 'select_missing_word',
    section: 'grammar',
    difficulty: 19,
    instruction: 'Pick the best option.',
    prompt: '把书放在桌子上。(bǎ shū fàng zài zhuōzi ___ )',
    choices: ['上 (shàng)', '下 (xià)', '里 (lǐ)', '外 (wài)'],
    correctChoice: '上 (shàng)',
  },
  {
    id: 'zh-9',
    kind: 'choose_translation',
    section: 'phrases',
    difficulty: 21,
    instruction: 'Choose the best translation.',
    prompt: '没关系 (méi guānxi)',
    choices: ['It doesn\'t matter / No problem', 'I disagree', 'Be careful', 'Long time no see'],
    correctChoice: 'It doesn\'t matter / No problem',
  },
  {
    id: 'zh-10',
    kind: 'multiple_choice',
    section: 'comprehension',
    difficulty: 23,
    instruction: 'What is implied?',
    prompt: '要是我早知道，就不会来了。(yàoshi wǒ zǎo zhīdào, jiù bù huì lái le)',
    choices: ['I came but wish I hadn\'t.', 'I knew and stayed home.', 'I will come later.', 'I never wanted to come.'],
    correctChoice: 'I came but wish I hadn\'t.',
  },
  {
    id: 'zh-11',
    kind: 'select_missing_word',
    section: 'grammar',
    difficulty: 24,
    instruction: 'Pick the most natural option.',
    prompt: '他跑得___我快。(tā pǎo de ___ wǒ kuài)',
    choices: ['比 (bǐ)', '和 (hé)', '在 (zài)', '对 (duì)'],
    correctChoice: '比 (bǐ)',
  },
  {
    id: 'zh-12',
    kind: 'choose_translation',
    section: 'vocabulary',
    difficulty: 10,
    instruction: 'Choose the best translation.',
    prompt: '谢谢 (xièxie)',
    choices: ['Thank you', 'Hello', 'Excuse me', 'Good night'],
    correctChoice: 'Thank you',
  },
];

const russian: LocalPlacementQuestion[] = [
  {
    id: 'ru-1',
    kind: 'choose_translation',
    section: 'vocabulary',
    difficulty: 4,
    instruction: 'Choose the best translation.',
    prompt: 'привет',
    choices: ['hi / hello', 'goodbye', 'thanks', 'please'],
    correctChoice: 'hi / hello',
  },
  {
    id: 'ru-2',
    kind: 'select_missing_word',
    section: 'grammar',
    difficulty: 7,
    instruction: 'Pick the word that fits.',
    prompt: 'Я ___ в Москве.',
    choices: ['живу', 'живёт', 'живёте', 'живут'],
    correctChoice: 'живу',
  },
  {
    id: 'ru-3',
    kind: 'choose_translation',
    section: 'phrases',
    difficulty: 9,
    instruction: 'Choose the best translation.',
    prompt: 'Как дела?',
    choices: ['How are you?', 'What is your name?', 'Where are you from?', 'See you!'],
    correctChoice: 'How are you?',
  },
  {
    id: 'ru-4',
    kind: 'multiple_choice',
    section: 'comprehension',
    difficulty: 12,
    instruction: 'What does it mean?',
    prompt: 'Я вчера работал дома.',
    choices: ['I worked at home yesterday.', 'I work at home every day.', 'I will work tomorrow.', 'I never work at home.'],
    correctChoice: 'I worked at home yesterday.',
  },
  {
    id: 'ru-5',
    kind: 'select_missing_word',
    section: 'grammar',
    difficulty: 14,
    instruction: 'Pick the correct form.',
    prompt: 'Если бы у меня было время, я ___ больше путешествовал.',
    choices: ['бы', 'буду', 'был', 'б'],
    correctChoice: 'бы',
  },
  {
    id: 'ru-6',
    kind: 'choose_translation',
    section: 'vocabulary',
    difficulty: 16,
    instruction: 'Choose the best translation.',
    prompt: 'однако',
    choices: ['however', 'because', 'always', 'under'],
    correctChoice: 'however',
  },
  {
    id: 'ru-7',
    kind: 'multiple_choice',
    section: 'comprehension',
    difficulty: 18,
    instruction: 'Choose the closest meaning.',
    prompt: 'Он отказался от предложения.',
    choices: ['He declined the offer.', 'He accepted the offer.', 'He made an offer.', 'He forgot the offer.'],
    correctChoice: 'He declined the offer.',
  },
  {
    id: 'ru-8',
    kind: 'select_missing_word',
    section: 'grammar',
    difficulty: 20,
    instruction: 'Pick the best option.',
    prompt: 'Книга, ___ я читал, была интересной.',
    choices: ['которую', 'который', 'которое', 'которые'],
    correctChoice: 'которую',
  },
  {
    id: 'ru-9',
    kind: 'choose_translation',
    section: 'phrases',
    difficulty: 22,
    instruction: 'Choose the best translation.',
    prompt: 'Дело не в этом.',
    choices: ['That\'s not the point.', 'That\'s correct.', 'That\'s impossible.', 'That\'s my job.'],
    correctChoice: 'That\'s not the point.',
  },
  {
    id: 'ru-10',
    kind: 'multiple_choice',
    section: 'comprehension',
    difficulty: 24,
    instruction: 'What is implied?',
    prompt: 'Знай я раньше, уехал бы пораньше.',
    choices: ['I learned too late.', 'I knew and left early.', 'I never left.', 'I will leave soon.'],
    correctChoice: 'I learned too late.',
  },
  {
    id: 'ru-11',
    kind: 'select_missing_word',
    section: 'grammar',
    difficulty: 11,
    instruction: 'Pick the correct case.',
    prompt: 'Я вижу ___ .',
    choices: ['кота', 'кот', 'коту', 'котом'],
    correctChoice: 'кота',
  },
  {
    id: 'ru-12',
    kind: 'choose_translation',
    section: 'vocabulary',
    difficulty: 8,
    instruction: 'Choose the best translation.',
    prompt: 'спасибо',
    choices: ['thank you', 'please', 'sorry', 'hello'],
    correctChoice: 'thank you',
  },
];

export const PLACEMENT_LOCAL_BANK: Record<CompanionChatApiLanguage, LocalPlacementQuestion[]> = {
  english,
  french,
  german,
  chinese,
  russian,
};
